location           = "southeastasia"
resource_group_name = "rg-kubeflow"
vm_size           = "Standard_E4s_v5"
admin_username    = "azureuser"
ssh_key_filename  = "vm_key.pem"
os_disk_type      = "Premium_LRS" 